### ISSUE TITLE
`quasar build darwin` is broken

### ISSUE THREAD

**Issue by oozzal** [quasarframework/electron-wrapper#2]
I'm not able to open the Application packaged with `quasar build darwin`.

Electron debug shows the following stacktrace:
```shell
$ electron --debug="4444" QuasarElectronApp.app/Contents/MacOS/QuasarElectronApp
App threw an error during load
/Users/uzzaldevkota/dev/oozzal/quasar/electron/dist/QuasarElectronApp-darwin-x64/QuasarElectronApp.app/Contents/MacOS/QuasarElectronApp:1
(function (exports, require, module, __filename, __dirname, process, global) { ����
                                                                               ^
SyntaxError: Invalid or unexpected token
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at loadApplicationPackage (/Users/uzzaldevkota/.nvm/versions/node/v6.5.0/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:280:12)
    at Object.<anonymous> (/Users/uzzaldevkota/.nvm/versions/node/v6.5.0/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:322:5)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
```
@rstoenescu

**Comment by rstoenescu** [comment]
There must be something with your App. Just re-checked and it works on the default starter kit. I remember an issue with Electron on this. Please check their forums. Thanks!

**Comment by oozzal** [comment]
Yes, it works with the default starter kit and with same version of `electron` and `node` as used on this project. Could there be anything wrong with the `electron.js` used in this wrapper?

**Comment by rstoenescu** [comment]
100% not.

This is a pure electron issue. Those ` ����` characters are there because of Electron and it's causing the App to issue error.
Did a quick search: example app with same problem: https://github.com/atom/autocomplete-plus/issues/799
Another one: http://www.itgo.me/a/x6882650637219895287/app-threw-an-error-when-running-syntaxerror-unexpected-token-import

It's something within your app. Can you remove piece by piece until you find the culprit and report back pls? We could use an addition to the troubleshoot and tips section..

Would help you directly on this issue but currently don't have time at all :(

**Comment by oozzal** [comment]
@rstoenescu Yeah, this was not an issue with `electron-wrapper` but with some configs on `app-template-default`. Here's a PR with the fix: https://github.com/quasarframework/app-template-default/pull/14
