### ISSUE TITLE
Modules won't load after build

### ISSUE THREAD

**Issue by qq7** [quasarframework/electron-wrapper#4]
Steps to reproduce:
1. quasar init
2. npm i
3. quasar wrap electron
4. quasar build
5. cd electron
6. npm i
7. npm i messenger
8. in electron.js
`const messenger = require('messenger');`
9. npm build // i've tested for both darwin and linux, neither of them load modules
10. cd dist & cd QuasarElectronApp-linux-x64
11. ./QuasarElectronApp

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'messenger'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/home/qq7/issue_quasar/yo/electron/dist/QuasarElectronApp-linux-x64/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /home/qq7/issue_quasar/yo/electron/dist/QuasarElectronApp-linux-x64/resources/app.asar/electron.js:7:19
    at Object.<anonymous> (/home/qq7/issue_quasar/yo/electron/dist/QuasarElectronApp-linux-x64/resources/app.asar/electron.js:63:2)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

**Comment by zuck** [comment]
I'm not sure it's the same issue, but even to try importing node's `fs` module fails with:

```
 ERROR  Failed to compile with 1 errors                               7:15:45 PM

This dependency was not found in node_modules:

* fs

Did you forget to run npm install --save for it?
```

**Comment by smolinari** [comment]
Hi,

I could verify the issue. It will take a bit, before we can find the cause and a solution, so the fix won't be in the next version. Please be patient. We'll get back to this as soon as possible.

Scott

**Comment by rstoenescu** [comment]
Please try out the new Electron wrapper. Just pushed a commit to it which should fix this. Thanks!
